// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: journal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(debit_cents - credit_cents), 0)::bigint AS balance_cents
FROM journal_lines
WHERE tenant_id = $1 AND account_id = $2
`

type GetAccountBalanceParams struct {
	TenantID  int64 `json:"tenant_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.TenantID, arg.AccountID)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const getJournalByIdempotencyKey = `-- name: GetJournalByIdempotencyKey :one
SELECT id, tenant_id, number, entry_date, period_id, status, description,
       source_ref, intent_type, idempotency_key, reversal_of_id,
       void_reason, voided_by, voided_at, hash, prev_hash,
       created_by, created_at, updated_at
FROM journal_entries
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetJournalByIdempotencyKeyParams struct {
	TenantID       int64       `json:"tenant_id"`
	IdempotencyKey pgtype.UUID `json:"idempotency_key"`
}

func (q *Queries) GetJournalByIdempotencyKey(ctx context.Context, arg GetJournalByIdempotencyKeyParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.EntryDate,
		&i.PeriodID,
		&i.Status,
		&i.Description,
		&i.SourceRef,
		&i.IntentType,
		&i.IdempotencyKey,
		&i.ReversalOfID,
		&i.VoidReason,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.Hash,
		&i.PrevHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, tenant_id, number, entry_date, period_id, status, description,
       source_ref, intent_type, idempotency_key, reversal_of_id,
       void_reason, voided_by, voided_at, hash, prev_hash,
       created_by, created_at, updated_at
FROM journal_entries
WHERE tenant_id = $1 AND id = $2
`

type GetJournalEntryParams struct {
	TenantID int64 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.TenantID, arg.ID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.EntryDate,
		&i.PeriodID,
		&i.Status,
		&i.Description,
		&i.SourceRef,
		&i.IntentType,
		&i.IdempotencyKey,
		&i.ReversalOfID,
		&i.VoidReason,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.Hash,
		&i.PrevHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (
    tenant_id, number, entry_date, period_id, description,
    source_ref, intent_type, idempotency_key, hash, prev_hash, created_by, request_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, number, entry_date, period_id, status, description,
          source_ref, intent_type, idempotency_key, reversal_of_id,
          void_reason, voided_by, voided_at, hash, prev_hash,
          created_by, created_at, updated_at
`

type InsertJournalEntryParams struct {
	TenantID       int64       `json:"tenant_id"`
	Number         string      `json:"number"`
	EntryDate      pgtype.Date `json:"entry_date"`
	PeriodID       int64       `json:"period_id"`
	Description    pgtype.Text `json:"description"`
	SourceRef      pgtype.Text `json:"source_ref"`
	IntentType     pgtype.Text `json:"intent_type"`
	IdempotencyKey pgtype.UUID `json:"idempotency_key"`
	Hash           string      `json:"hash"`
	PrevHash       string      `json:"prev_hash"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
	RequestHash    pgtype.Text `json:"request_hash"`
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.TenantID,
		arg.Number,
		arg.EntryDate,
		arg.PeriodID,
		arg.Description,
		arg.SourceRef,
		arg.IntentType,
		arg.IdempotencyKey,
		arg.Hash,
		arg.PrevHash,
		arg.CreatedBy,
		arg.RequestHash,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.EntryDate,
		&i.PeriodID,
		&i.Status,
		&i.Description,
		&i.SourceRef,
		&i.IntentType,
		&i.IdempotencyKey,
		&i.ReversalOfID,
		&i.VoidReason,
		&i.VoidedBy,
		&i.VoidedAt,
		&i.Hash,
		&i.PrevHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJournalLine = `-- name: InsertJournalLine :exec
INSERT INTO journal_lines (
    tenant_id, entry_id, account_id, debit_cents, credit_cents,
    description, source_line_ref, dimension_ids
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertJournalLineParams struct {
	TenantID      int64       `json:"tenant_id"`
	EntryID       int64       `json:"entry_id"`
	AccountID     int64       `json:"account_id"`
	DebitCents    int64       `json:"debit_cents"`
	CreditCents   int64       `json:"credit_cents"`
	Description   pgtype.Text `json:"description"`
	SourceLineRef pgtype.Text `json:"source_line_ref"`
	DimensionIds  []byte      `json:"dimension_ids"`
}

func (q *Queries) InsertJournalLine(ctx context.Context, arg InsertJournalLineParams) error {
	_, err := q.db.Exec(ctx, insertJournalLine,
		arg.TenantID,
		arg.EntryID,
		arg.AccountID,
		arg.DebitCents,
		arg.CreditCents,
		arg.Description,
		arg.SourceLineRef,
		arg.DimensionIds,
	)
	return err
}

const lockLedgerChainHead = `-- name: LockLedgerChainHead :one
SELECT tenant_id, last_journal_id, last_hash, updated_at
FROM ledger_chain_heads
WHERE tenant_id = $1
FOR UPDATE
`

func (q *Queries) LockLedgerChainHead(ctx context.Context, tenantID int64) (LedgerChainHead, error) {
	row := q.db.QueryRow(ctx, lockLedgerChainHead, tenantID)
	var i LedgerChainHead
	err := row.Scan(
		&i.TenantID,
		&i.LastJournalID,
		&i.LastHash,
		&i.UpdatedAt,
	)
	return i, err
}
