// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int64       `json:"id"`
	TenantID    int64       `json:"tenant_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	ReportGroup string      `json:"report_group"`
	AccountType string      `json:"account_type"`
	ParentID    pgtype.Int8 `json:"parent_id"`
	IsGroup     bool        `json:"is_group"`
	IsActive    bool        `json:"is_active"`
	ValidFrom   pgtype.Date `json:"valid_from"`
	ValidTo     pgtype.Date `json:"valid_to"`
}

type AccountingPeriod struct {
	ID              int64              `json:"id"`
	TenantID        int64              `json:"tenant_id"`
	PeriodStart     pgtype.Date        `json:"period_start"`
	PeriodEnd       pgtype.Date        `json:"period_end"`
	Status          string             `json:"status"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	ClosedBy        pgtype.Int8        `json:"closed_by"`
	UnlockRequested bool               `json:"unlock_requested"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	TenantID   int64              `json:"tenant_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	BeforeJson []byte             `json:"before_json"`
	AfterJson  []byte             `json:"after_json"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID                     int64       `json:"id"`
	TenantID               int64       `json:"tenant_id"`
	Name                   string      `json:"name"`
	Direction              string      `json:"direction"`
	DefaultDebitAccountID  pgtype.Int8 `json:"default_debit_account_id"`
	DefaultCreditAccountID pgtype.Int8 `json:"default_credit_account_id"`
	IsActive               bool        `json:"is_active"`
}

type DocumentNumbering struct {
	ID         int64  `json:"id"`
	TenantID   int64  `json:"tenant_id"`
	DocType    string `json:"doc_type"`
	Prefix     string `json:"prefix"`
	LastSeq    int64  `json:"last_seq"`
	FiscalYear int32  `json:"fiscal_year"`
}

type JournalEntry struct {
	ID             int64              `json:"id"`
	TenantID       int64              `json:"tenant_id"`
	Number         string             `json:"number"`
	EntryDate      pgtype.Date        `json:"entry_date"`
	PeriodID       int64              `json:"period_id"`
	Status         string             `json:"status"`
	Description    pgtype.Text        `json:"description"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	IntentType     pgtype.Text        `json:"intent_type"`
	IdempotencyKey pgtype.UUID        `json:"idempotency_key"`
	ReversalOfID   pgtype.Int8        `json:"reversal_of_id"`
	VoidReason     pgtype.Text        `json:"void_reason"`
	VoidedBy       pgtype.Int8        `json:"voided_by"`
	VoidedAt       pgtype.Timestamptz `json:"voided_at"`
	Hash           string             `json:"hash"`
	PrevHash       string             `json:"prev_hash"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JournalLine struct {
	ID            int64       `json:"id"`
	TenantID      int64       `json:"tenant_id"`
	EntryID       int64       `json:"entry_id"`
	AccountID     int64       `json:"account_id"`
	DebitCents    int64       `json:"debit_cents"`
	CreditCents   int64       `json:"credit_cents"`
	Description   pgtype.Text `json:"description"`
	SourceLineRef pgtype.Text `json:"source_line_ref"`
	DimensionIds  []byte      `json:"dimension_ids"`
}

type LedgerChainHead struct {
	TenantID      int64              `json:"tenant_id"`
	LastJournalID pgtype.Int8        `json:"last_journal_id"`
	LastHash      string             `json:"last_hash"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	Topic        string             `json:"topic"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

type ReportMapping struct {
	ID         int64  `json:"id"`
	TenantID   int64  `json:"tenant_id"`
	AccountID  int64  `json:"account_id"`
	ReportType string `json:"report_type"`
	ReportLine string `json:"report_line"`
	Priority   int32  `json:"priority"`
}

type Tenant struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	CurrencyCode    string             `json:"currency_code"`
	FiscalYearStart pgtype.Date        `json:"fiscal_year_start"`
	PeriodType      string             `json:"period_type"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	FullName     string             `json:"full_name"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserTenant struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	TenantID int64  `json:"tenant_id"`
	Role     string `json:"role"`
}
